sh submit_6_16cores_16G_do_not_tackle_200_paragraphs.sh
sh exe_core_combine_32G_4executors_16cores_yarn.sh
sh exe_core_combine_16G_8executors_8cores_yarn.sh
sh exe_core_combine_8G_16executors_4cores_yarn.sh
sh exe_core_combine_4G_32executors_2cores_yarn.sh
sh submit_2G_4cores_16executors_yarn.sh 
ls
